### ISSUE TITLE
ambiguity issue with GCC

### ISSUE THREAD

**Issue by mgieseki** [cbeck88/strict-variant#2]
Thank you for providing your implementation of `variant`. I'm just playing around with it and stumbled over an issue. The following code builds with Clang but fails with GCC (5, 6, 7) due to an ambiguity of `initializer<T>::operator()`:

```cpp
struct S {
    explicit S (const std::string &str) {}
};

strict_variant::variant<std::string, S> var{std::string("string")};
```
```
variant.hpp:241:37: error: request for member ‘operator()’ is ambiguous
     return decltype(initializer<T>{}(std::declval<T>()))::value;
```
Is this intentional behavior or a bug? The code builds correctly with `boost::variant`.

**Comment by cbeck88** [comment]
Interesting, I didn't know about this. I will look into it.

**Comment by cbeck88** [comment]
Hey, sorry I didn't write back yet, I didn't forget about this, I just didn't have much time recently, I just started a new job. Will look into it soon :)

**Comment by mgieseki** [comment]
That's ok. It's not urgent to me. Thanks for having a look into this issue, and good luck with the new job.

**Comment by cbeck88** [comment]
Thanks for reporting the issue and getting it fixed! I'm going to close this now, it appears to me to be fixed
